site_name: CRandom
site_url: https://k4zoku.github.io/crandom/
repo_url: https://github.com/k4zoku/crandom
docs_dir: docs/markdown
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.footer
    - announce.dismiss
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: material/github

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - social

extra:
  social:
    - icon: material/github
      link: https://github.com/K4zoku
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/390496098051162114
