.TH "src Directory Reference" 3 "Version 1.0.0" "CRandom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcrandom\&.h\fP"
.br
.ti -1c
.RI "file \fBrandom_device\&.h\fP"
.br
.ti -1c
.RI "file \fBxoshiro256ss\&.h\fP"
.br
.in -1c
